export { HomePage, clickAndGotoHomePage, clickAndGotoPage } from './pages/HomePage'
export { Locators } from './pages/Locators'
export { TextInputTestPage } from './pages/TextInputTestPage'
export { appiumDriver } from './testsetup'
export { AnyPage } from './pages/AnyPage'
export { TestPage } from './pages/TestPage'
